config/routes.rb
Myftu::Application.routes.draw do

  devise_for :users

  root :to => "static#index"

  # Airplanes
  resources :airplanes, :path => "aircraft" do
    resources :flights
    resources :bookings
    resources :snags
  end
end

app/models/address.rb
class Addresses < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/aircraft_manufacturer.rb
class AircraftManufacturer < ActiveRecord::Base
  has_many :aircraft_models
  has_many :airplanes
  has_many :flights, :through => :airplanes
  has_many :bookings, :through => :airplanes
  has_many :operators, :through => :airplanes

end

app/models/aircraft_model.rb
class AircraftModel < ActiveRecord::Base
  belongs_to :manufacturer, :class_name => "AircraftManufacturer"
  has_many :models, :through => :manufacturer, :class_name => "AircraftModel"

end

app/models/airplane.rb
class Airplane < ActiveRecord::Base
  belongs_to :user
  belongs_to :manufacturer, :class_name => "AircraftManufacturer"
  belongs_to :model, :class_name => "AircraftModel"
  has_one :operator, :through => :user
  has_many :bookings
  has_many :flights
  has_many :snags
  has_many :notes, :as => :notable
  has_many :photos, :as => :picturable

  attr_accessible :manufacturer_name, :model_name, :serial_number, :registration, :year

  attr_accessor :manufacturer_name, :model_name

  def aircraft_type
    parts = []
    parts << manufacturer.name if manufacturer.present?
    parts << model.name if model.present?
    parts.compact.join(" ")
  end

  def title
    @title || registration
  end

  def to_param
    "#{id} #{registration}".parameterize
  end



end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :airplane

end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :airplane
  belongs_to :operator
  has_one :user, :through => :airplane
end

app/models/operator.rb
class Operator < ActiveRecord::Base
  belongs_to :owner, :class_name => "User"
  has_one :address, :as => :addressable
  has_many :bookings
  has_many :flights
  has_many :airplanes
  has_many :aircraft_types, :through => :airplanes
  has_many :pilots
  has_many :instructors
  has_many :dispatchers

  validates_presence_of :name
  validates_presence_of :owner

  attr_protected :owner_id, :created_at, :updated_at, :status

end

app/models/pilot.rb
class Pilot < User

end

app/models/snag.rb
class Snag < ActiveRecord::Base
  belongs_to :airplane
  belongs_to :flight
  belongs_to :reporter, :class_name => "User"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController

  def index
    @airplanes = Airplane.all
  end

  def show
    @airplane = Airplane.find params[:id]
  end

  def new
    @airplane = Airplane.new(params[:airplane])
  end

  def create
    @airplane = Airplane.new(params[:airplane])
    if @airplane.save
      redirect_to @airplane, :flash => { :success => "Aircraft has been created" }
    else
      redirect_to new_airplane_path(:airplane => params[:airplane])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def application_page_title
    "MyFTU.com"
  end
end

app/views/airplanes/index.html.haml
.row
  .span12
    .page-header
      %h1
        Aircraft
    .btn-toolbar
      .btn-group
        = link_to new_airplane_path, :class => "btn" do
          %i.icon-plus-sign
          New Aircraft

    = render "airplanes/index/table"

app/views/airplanes/index/_table.html.haml
%table.table.table-bordered.table-striped.table-condensed
  %thead
    %tr
      %th Registration
      %th Aircraft Type

  %tbody
    - for airplane in @airplanes
      %tr
        %td= link_to airplane.registration, airplane
        %td= link_to airplane.aircraft_type, airplane

app/views/airplanes/new.html.haml
.row
  .span12
    .page-header
      %h1 New Aircraft

    = form_for @airplane do |f|
      = f.label :manufacturer_title
      = f.text_field :manufacturer_title
      = f.label :model_title
      = f.text_field :model_title
      = f.label :registration
      = f.text_field :registration
      = f.label :serial_number
      = f.text_field :serial_number

      .form-actions
        = f.submit "Create", :class => "btn btn-success"
        or
        = link_to "Cancel", airplanes_path

app/views/airplanes/show.html.haml
.row
  .span12
    .page-header
      %h1= @airplane.title

app/views/layouts/application.html.haml
!!!
%html
  %head= render "shared/head"
  %body
    .container
      #site-header= render "shared/header"
      #site-content
      = render "shared/flash_messages"
      = yield
      .clearfix

    #site-footer
      .container= render "shared/footer"

app/views/shared/_head.html.haml
%title= application_page_title
= stylesheet_link_tag    "application", :media => "all"
= javascript_include_tag "application"
= yield :extra_javascript_includes
= csrf_meta_tags

app/views/shared/_header.html.haml
.row
  .span12
    .navbar
      .navbar-inner
        .brand= link_to "MyFTU.com", root_path
        %ul.nav
          %li= link_to "Aircraft", airplanes_path